trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'Build'

- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: dotnet publish --configuration Release --output publish
      displayName: 'Publish'
      
